#!/usr/bin/env python3
"""
Translate English responses to native language using TranslateGemma.

Reads the Setting-1 (English) responses generated by
``generate_translate_dpo_responses.py``, translates the thinking trace and
the final answer separately (preserving ``<think>…</think>`` structure),
and writes the translated response alongside the original data.

Output is written to ``data/translate_dpo/translated/{LANG}_translated.jsonl``.

Usage::

    # Direct GPU inference (recommended — no vLLM server needed):
    python data/translate_with_gemma.py --language JA_JP --gpu 1
    python data/translate_with_gemma.py --gpu 1             # all languages

    # Legacy vLLM mode:
    python data/translate_with_gemma.py --language JA_JP --port 8401
    python data/translate_with_gemma.py --language JA_JP --max_samples 50
"""

import argparse
import json
import logging
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

import yaml
from tqdm import tqdm

try:
    import openai
except ImportError:
    openai = None  # only needed for vLLM mode

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from prompts.translate_dpo_prompts import get_translate_dpo_prompts

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------


def _setup_logger(name: str, log_dir: Path, filename: str) -> logging.Logger:
    log_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()

    fh = logging.FileHandler(log_dir / filename, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s", datefmt="%H:%M:%S"
    ))
    logger.addHandler(fh)

    sh = logging.StreamHandler()
    sh.setLevel(logging.INFO)
    sh.setFormatter(logging.Formatter("[%(name)s] %(message)s"))
    logger.addHandler(sh)

    return logger


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)


def _load_config(config_path: str) -> dict:
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def _load_jsonl(path: Path) -> list[dict]:
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _split_response(response: str) -> Tuple[str, str]:
    """Split a response into (thinking_trace, final_answer).

    Returns ``("", response)`` when no ``<think>`` block is present.
    """
    match = _THINK_RE.search(response)
    if match:
        thinking = match.group(1).strip()
        answer = response[match.end():].strip()
        return thinking, answer
    return "", response.strip()


# ---------------------------------------------------------------------------
# Shared language mappings
# ---------------------------------------------------------------------------

# Maps project language codes → ISO 639-1 codes used by TranslateGemma.
_TRANSLATE_LANG_CODE: dict[str, str] = {
    "JA_JP": "ja",
    "BN_BD": "bn",
    "SW_KE": "sw",
}

# ISO 639-1 → human-readable language name (must match TranslateGemma's
# internal mapping so that the prompt is identical to what its chat template
# would produce).
_ISO_LANG_NAME: dict[str, str] = {
    "en": "English",
    "ja": "Japanese",
    "bn": "Bengali",
    "sw": "Swahili",
}


# ---------------------------------------------------------------------------
# Direct GPU inference (TranslateGemma loaded in-process)
# ---------------------------------------------------------------------------


class DirectTranslator:
    """Loads TranslateGemma on a specific CUDA device and translates text
    using ``model.generate()`` directly — no vLLM server required.
    """

    def __init__(self, model_id: str, gpu_id: int) -> None:
        import torch
        from transformers import AutoModelForImageTextToText, AutoProcessor

        self.model_id = model_id
        self.gpu_id = gpu_id
        self.device = torch.device(f"cuda:{gpu_id}")

        self.processor = AutoProcessor.from_pretrained(model_id)
        self.model = AutoModelForImageTextToText.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16,
            device_map=self.device,
        )
        self.model.eval()

    # -- public API ----------------------------------------------------------

    def translate(
        self,
        text: str,
        target_lang_code: str,
        source_lang_code: str = "en",
        max_new_tokens: int = 2048,
        temperature: float = 0.3,
        top_p: float = 0.95,
    ) -> str:
        """Translate *text* from *source_lang_code* to *target_lang_code*.

        Uses the processor's ``apply_chat_template`` so that the prompt
        exactly matches TranslateGemma's expected format (including the
        ``source_lang_code`` / ``target_lang_code`` metadata fields).
        """
        import torch

        if not text.strip():
            return ""

        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "source_lang_code": source_lang_code,
                        "target_lang_code": target_lang_code,
                        "text": text,
                    }
                ],
            }
        ]

        inputs = self.processor.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_dict=True,
            return_tensors="pt",
        ).to(self.device, dtype=torch.bfloat16)
        input_len = inputs["input_ids"].shape[1]

        gen_kwargs: dict = {"max_new_tokens": max_new_tokens, "do_sample": False}
        if temperature > 0 and temperature != 1.0:
            gen_kwargs.update(do_sample=True, temperature=temperature, top_p=top_p)

        with torch.inference_mode():
            output_ids = self.model.generate(**inputs, **gen_kwargs)

        # Decode only the newly generated tokens
        generated = output_ids[0][input_len:]
        return self.processor.decode(generated, skip_special_tokens=True).strip()

    def translate_response(
        self,
        english_response: str,
        target_lang_code: str,
        max_new_tokens: int = 2048,
        temperature: float = 0.3,
        top_p: float = 0.95,
    ) -> str:
        """Translate a full response, preserving ``<think>…</think>`` structure."""
        thinking, answer = _split_response(english_response)

        translated_thinking = self.translate(
            thinking, target_lang_code, max_new_tokens=max_new_tokens,
            temperature=temperature, top_p=top_p,
        )
        translated_answer = self.translate(
            answer, target_lang_code, max_new_tokens=max_new_tokens,
            temperature=temperature, top_p=top_p,
        )

        if translated_thinking:
            return f"<think>\n{translated_thinking}\n</think>\n{translated_answer}"
        return translated_answer


# ---------------------------------------------------------------------------
# Translation via vLLM / OpenAI-compatible API (legacy)
# ---------------------------------------------------------------------------


def _build_translate_prompt(
    text: str,
    target_lang_code: str,
    source_lang_code: str = "en",
) -> str:
    """Build the raw prompt string that reproduces TranslateGemma's chat template.

    vLLM's OpenAI-compatible chat API strips non-standard content-part fields
    (``source_lang_code``, ``target_lang_code``) that TranslateGemma's Jinja
    template requires, so we construct the prompt manually and use the
    completions API instead.
    """
    src_name = _ISO_LANG_NAME[source_lang_code]
    tgt_name = _ISO_LANG_NAME[target_lang_code]
    return (
        f"<bos><start_of_turn>user\n"
        f"You are a professional {src_name} ({source_lang_code}) to "
        f"{tgt_name} ({target_lang_code}) translator. "
        f"Your goal is to accurately convey the meaning and nuances of the "
        f"original {src_name} text while adhering to {tgt_name} grammar, "
        f"vocabulary, and cultural sensitivities.\n"
        f"Produce only the {tgt_name} translation, without any additional "
        f"explanations or commentary. "
        f"Please translate the following {src_name} text into {tgt_name}:"
        f"\n\n\n{text}<end_of_turn>\n"
        f"<start_of_turn>model\n"
    )


def translate_text(
    client: openai.OpenAI,
    model_name: str,
    text: str,
    target_lang_code: str,
    max_tokens: int = 8192,
    temperature: float = 0.3,
    top_p: float = 0.95,
) -> str:
    """Translate *text* from English to *target_lang_code* using TranslateGemma.

    Args:
        client: OpenAI client pointed at the TranslateGemma vLLM server.
        model_name: HuggingFace model ID for TranslateGemma.
        text: Source text in English.
        target_lang_code: ISO 639-1 language code (e.g. ``"ja"``, ``"bn"``,
            ``"sw"``).
        max_tokens: Maximum tokens for the translation output.
        temperature: Sampling temperature.
        top_p: Top-p nucleus sampling.

    Returns:
        The translated text.
    """
    if not text.strip():
        return ""

    prompt = _build_translate_prompt(text, target_lang_code)

    response = client.completions.create(
        model=model_name,
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
    )
    return (response.choices[0].text or "").strip()


def translate_response(
    client: openai.OpenAI,
    model_name: str,
    english_response: str,
    target_lang_code: str,
    max_tokens: int = 8192,
    temperature: float = 0.3,
    top_p: float = 0.95,
) -> str:
    """Translate a full English response (thinking + answer) to native language.

    The ``<think>…</think>`` structure is preserved: the thinking trace and
    the final answer are translated independently, then reassembled.
    """
    thinking, answer = _split_response(english_response)

    translated_thinking = translate_text(
        client, model_name, thinking, target_lang_code,
        max_tokens, temperature, top_p,
    )
    translated_answer = translate_text(
        client, model_name, answer, target_lang_code,
        max_tokens, temperature, top_p,
    )

    if translated_thinking:
        return f"<think>\n{translated_thinking}\n</think>\n{translated_answer}"
    return translated_answer


# ---------------------------------------------------------------------------
# Main translation logic
# ---------------------------------------------------------------------------


def merge_shards(
    language_code: str,
    output_dir: Path,
    num_shards: int,
) -> None:
    """Merge shard output files into a single ``{LANG}_translated.jsonl``."""
    merged: list[dict] = []
    for shard_id in range(num_shards):
        shard_path = output_dir / f"{language_code}_translated_shard{shard_id}.jsonl"
        if not shard_path.exists():
            raise FileNotFoundError(
                f"Shard file not found: {shard_path}. "
                f"Make sure all {num_shards} shards completed successfully."
            )
        merged.extend(_load_jsonl(shard_path))

    out_path = output_dir / f"{language_code}_translated.jsonl"
    with open(out_path, "w", encoding="utf-8") as fout:
        for rec in merged:
            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"[{language_code}] Merged {num_shards} shards → {out_path} ({len(merged)} records)")

    # Clean up shard files
    for shard_id in range(num_shards):
        shard_path = output_dir / f"{language_code}_translated_shard{shard_id}.jsonl"
        shard_path.unlink(missing_ok=True)


def translate_for_language(
    language_code: str,
    config: dict,
    input_dir: Path,
    output_dir: Path,
    port: Optional[int] = None,
    gpu: Optional[int] = None,
    max_samples: int | None = None,
    n_workers: int = 4,
    shard_id: Optional[int] = None,
    num_shards: int = 1,
) -> None:
    """Translate all English responses for one language.

    Either *gpu* (direct inference) or *port* (vLLM server) must be given.
    When *gpu* is set, the model is loaded in-process on the specified CUDA
    device and records are translated sequentially.  When *port* is set,
    translation is done via a running vLLM server with concurrent workers.

    When *shard_id* is not None, only processes a 1/*num_shards* slice of
    the dataset and writes to a shard-specific output file.
    """
    shard_suffix = f"_shard{shard_id}" if shard_id is not None else ""
    log_dir = PROJECT_ROOT / "outputs-translate_dpo" / "logs"
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    logger = _setup_logger(
        name=f"translate.{language_code}{shard_suffix}",
        log_dir=log_dir,
        filename=f"translate_{language_code}{shard_suffix}_{ts}.log",
    )

    # Map project language code (e.g. JA_JP) to ISO code (e.g. ja)
    if language_code not in _TRANSLATE_LANG_CODE:
        raise ValueError(
            f"Unsupported language code: {language_code!r}. "
            f"Supported: {list(_TRANSLATE_LANG_CODE)}"
        )
    target_lang_code = _TRANSLATE_LANG_CODE[language_code]

    prompts = get_translate_dpo_prompts(language_code)
    target_language = prompts["language_name"]

    # Load raw responses
    input_path = input_dir / f"{language_code}_responses.jsonl"
    if not input_path.exists():
        raise FileNotFoundError(
            f"Raw responses not found: {input_path}. "
            "Run generate_translate_dpo_responses.py first."
        )
    records = _load_jsonl(input_path)
    if max_samples is not None:
        records = records[:max_samples]

    # --- Shard slicing ------------------------------------------------------
    total_records = len(records)
    if shard_id is not None:
        shard_size = (total_records + num_shards - 1) // num_shards  # ceil div
        start = shard_id * shard_size
        end = min(start + shard_size, total_records)
        records = records[start:end]
        logger.info(
            "Shard %d/%d: records [%d, %d) of %d",
            shard_id, num_shards, start, end, total_records,
        )

    logger.info("Loaded %d records from %s", len(records), input_path)

    # Translation config
    trans_cfg = config.get("translation", {})
    max_tokens = trans_cfg.get("max_tokens", 2048)
    temperature = trans_cfg.get("temperature", 0.3)
    top_p = trans_cfg.get("top_p", 0.95)

    # --- Prepare output -----------------------------------------------------
    output_dir.mkdir(parents=True, exist_ok=True)
    out_fname = f"{language_code}_translated{shard_suffix}.jsonl"
    out_path = output_dir / out_fname
    translated_records: list[dict] = [None] * len(records)  # preserve order

    # ========================================================================
    # Direct GPU inference path
    # ========================================================================
    if gpu is not None:
        model_id = config["models"]["translation_model"]
        logger.info(
            "Direct GPU inference: model=%s, GPU=%d, lang=%s (%s)",
            model_id, gpu, target_language, target_lang_code,
        )

        translator = DirectTranslator(model_id, gpu_id=gpu)
        logger.info("Model loaded on cuda:%d", gpu)

        for i, record in enumerate(
            tqdm(records, desc=f"[{language_code}] translate (GPU {gpu})", unit="ex")
        ):
            translated_response = translator.translate_response(
                record["english_response"],
                target_lang_code,
                max_new_tokens=max_tokens,
                temperature=temperature,
                top_p=top_p,
            )
            rec = dict(record)
            rec["translated_response"] = translated_response
            translated_records[i] = rec

            logger.debug("idx=%d | translated=%s", i, translated_response[:200])

            if i % 10 == 0:
                logger.info(
                    "\n========== SAMPLE idx=%d ==========\n"
                    "[ENGLISH RESPONSE]\n%s\n\n"
                    "[TRANSLATED RESPONSE]\n%s\n"
                    "====================================",
                    i, record["english_response"], translated_response,
                )

    # ========================================================================
    # vLLM server path (legacy)
    # ========================================================================
    elif port is not None:
        if openai is None:
            raise ImportError(
                "openai package is required for vLLM mode. "
                "Install it with: pip install openai"
            )

        client = openai.OpenAI(
            base_url=f"http://localhost:{port}/v1", api_key="EMPTY"
        )
        available = client.models.list()
        model_name = (
            available.data[0].id
            if available.data
            else config["models"]["translation_model"]
        )

        logger.info("TranslateGemma server: http://localhost:%d/v1", port)
        logger.info("Model: %s", model_name)
        logger.info("Target language: %s (%s)", target_language, target_lang_code)

        def _translate_one(idx: int, record: dict) -> Tuple[int, str]:
            translated = translate_response(
                client, model_name, record["english_response"],
                target_lang_code,
                max_tokens, temperature, top_p,
            )
            return idx, translated

        tqdm_desc = f"[{language_code}{shard_suffix}] translate (port {port})"
        with ThreadPoolExecutor(max_workers=n_workers) as pool:
            futures = {
                pool.submit(_translate_one, i, r): i
                for i, r in enumerate(records)
            }
            for fut in tqdm(
                as_completed(futures),
                total=len(futures),
                desc=tqdm_desc,
                unit="ex",
            ):
                idx, translated_response = fut.result()
                rec = dict(records[idx])
                rec["translated_response"] = translated_response
                translated_records[idx] = rec

                logger.debug(
                    "idx=%d | translated=%s", idx, translated_response[:200]
                )
                if idx % 10 == 0:
                    logger.info(
                        "\n========== SAMPLE idx=%d ==========\n"
                        "[ENGLISH RESPONSE]\n%s\n\n"
                        "[TRANSLATED RESPONSE]\n%s\n"
                        "====================================",
                        idx, records[idx]["english_response"],
                        translated_response,
                    )
    else:
        raise ValueError("Either --gpu or --port must be specified.")

    # --- Write output -------------------------------------------------------
    with open(out_path, "w", encoding="utf-8") as fout:
        for rec in translated_records:
            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")

    logger.info("Translation complete: %d records → %s", len(records), out_path)
    print(f"[{language_code}] {len(records)} translated → {out_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Translate English responses to native language "
                    "using TranslateGemma for the Translate-DPO experiment."
    )
    parser.add_argument(
        "--language", type=str, default=None,
        help="Language code (e.g. JA_JP). If omitted, run all.",
    )
    parser.add_argument(
        "--config", type=str,
        default=str(PROJECT_ROOT / "configs" / "translate_dpo_config.yaml"),
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--gpu", type=int, default=None,
        help="CUDA device ID for direct GPU inference (recommended). "
             "Loads TranslateGemma in-process — no vLLM server needed.",
    )
    group.add_argument(
        "--port", type=int, default=None,
        help="vLLM server port for TranslateGemma (legacy mode).",
    )
    parser.add_argument(
        "--n_workers", type=int, default=4,
        help="Number of concurrent translation threads (vLLM mode only).",
    )
    parser.add_argument(
        "--max_samples", type=int, default=None,
        help="Max records to translate (for debugging).",
    )
    parser.add_argument(
        "--shard_id", type=int, default=None,
        help="Shard index (0-based). When set, only processes the "
             "corresponding 1/num_shards slice of the dataset.",
    )
    parser.add_argument(
        "--num_shards", type=int, default=1,
        help="Total number of shards to split the dataset into.",
    )
    parser.add_argument(
        "--merge_shards", action="store_true",
        help="Merge previously written shard files into the final output. "
             "Requires --language and --num_shards.",
    )
    args = parser.parse_args()

    config = _load_config(args.config)
    input_dir = PROJECT_ROOT / "data" / "translate_dpo" / "raw"
    output_dir = PROJECT_ROOT / "data" / "translate_dpo" / "translated"

    # --- Merge mode ---------------------------------------------------------
    if args.merge_shards:
        languages = (
            [args.language] if args.language
            else [l["code"] for l in config["languages"]]
        )
        for lang in languages:
            merge_shards(lang, output_dir, args.num_shards)
        return

    # --- Translate mode -----------------------------------------------------
    # Resolve inference mode
    gpu = args.gpu
    port = args.port
    if gpu is None and port is None:
        # Default to vLLM port from config if neither is specified
        port = config["vllm_ports"]["translation"]

    languages = (
        [args.language] if args.language
        else [l["code"] for l in config["languages"]]
    )
    for lang in languages:
        translate_for_language(
            lang, config, input_dir, output_dir,
            port=port, gpu=gpu,
            max_samples=args.max_samples,
            n_workers=args.n_workers,
            shard_id=args.shard_id,
            num_shards=args.num_shards,
        )


if __name__ == "__main__":
    main()
